[package]
name = "local_video"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.7.0"
askama = "0.12.1"
futures-core = "0.3.30"
local-ip-address = "0.6.1"
regex = "1.10.5"
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.38.0", features = ["full"] }
